import {theme} from './theme';
import React,{useState,useEffect} from 'react';
import {View,Text,Image,TextInput,Pressable,ScrollView,KeyboardAvoidingView,Platform,StyleSheet} from 'react-native';
import Icon from './Icon';
const ink=theme.ink,cyan=theme.brand;
import {validateCode} from './auth';
export default function AuthScreen({step,email,setEmail,onRequest,onVerified,onBack}){
 const [code,setCode]=useState(''),[error,setError]=useState(''),[issuedAt,setIssuedAt]=useState(Date.now()),[remaining,setRemaining]=useState(0);
 useEffect(()=>{setError('');setCode('');if(step==='Verify'){setIssuedAt(Date.now());setRemaining(30)}},[step]);
 useEffect(()=>{if(!remaining)return;const timer=setTimeout(()=>setRemaining(n=>n-1),1000);return()=>clearTimeout(timer)},[remaining]);
 const verify=()=>{if(!validateCode(code,issuedAt)){setError(Date.now()-issuedAt>=300000?'This code has expired. Request another code.':'Enter the 6-digit demo code 123456.');return}setError('');onVerified();};
 const request=()=>{if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email.trim())){setError('Enter a valid email address.');return}setEmail(email.trim());setError('');onRequest();};
 return <KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==='ios'?'padding':undefined}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={s.page}><Pressable accessibilityRole="button" accessibilityLabel="Back" style={s.back} onPress={onBack}><Icon name="back"/></Pressable><Image source={require('../assets/logo-brand.webp')} resizeMethod="scale" style={s.logo}/><Text style={s.title}>{step==='Verify'?'Check your email':'Welcome back'}</Text><Text style={s.subtitle}>{step==='Verify'?'Enter the code to sign in to your trade account.':'Sign in to place or manage your orders'}</Text><View style={s.form}>{step==='Login'?<><Text style={s.label}>Email</Text><TextInput accessibilityLabel="Email" value={email} onChangeText={setEmail} onSubmitEditing={request} keyboardType="email-address" autoCapitalize="none" autoComplete="email" placeholder="name@company.com" style={s.input}/></>:<><Text style={s.label}>Verification code</Text><TextInput accessibilityLabel="Verification code" value={code} onChangeText={v=>setCode(v.replace(/\D/g,'').slice(0,6))} onSubmitEditing={verify} keyboardType="number-pad" textContentType="oneTimeCode" autoComplete="one-time-code" maxLength={6} placeholder="000000" style={[s.input,s.code]}/></>}{error!==''&&<Text accessibilityLiveRegion="polite" style={s.error}>{error}</Text>}<Pressable accessibilityRole="button" onPress={step==='Verify'?verify:request} style={s.button}><Text style={s.buttonText}>{step==='Verify'?'Verify & sign in':'Continue'}</Text></Pressable>{step==='Login'?<Pressable accessibilityRole="button" onPress={()=>setEmail('john@vue.example')}><Text style={s.link}>Use demo email</Text></Pressable>:<><Pressable accessibilityRole="button" disabled={remaining>0} onPress={()=>{setIssuedAt(Date.now());setCode('');setError('');setRemaining(30)}}><Text style={[s.link,remaining>0&&{color:'#879AA5'}]}>{remaining>0?`Resend code in ${remaining}s`:'Resend code'}</Text></Pressable><Pressable accessibilityRole="button" onPress={onBack}><Text style={s.link}>Change email address</Text></Pressable><View style={s.demo}><Text style={s.demoTitle}>Demo verification code: 123456</Text><Text style={s.note}>No email is sent in this mock app. The code is valid for 5 minutes.</Text></View></>}</View></ScrollView></KeyboardAvoidingView>
}
const s=StyleSheet.create({page:{padding:24,flexGrow:1},back:{position:'absolute',left:24,top:14,width:44,height:44,justifyContent:'center'},logo:{width:240,height:190,resizeMode:'contain',alignSelf:'center',marginTop:80},title:{fontSize:theme.type.title,fontWeight:'800',color:ink,textAlign:'center',marginTop:12},subtitle:{fontSize:theme.type.body,color:theme.muted,textAlign:'center',lineHeight:24,marginTop:8},form:{marginTop:58},label:{fontSize:16,fontWeight:'600',color:ink,marginBottom:8},input:{borderWidth:1,borderColor:'#A9BBC6',borderRadius:10,padding:14,color:ink,fontSize:theme.type.body,marginBottom:16},code:{fontSize:24,letterSpacing:12,textAlign:'center',height:66},recipient:{fontSize:theme.type.body,fontWeight:'600',color:ink,textAlign:'center',marginBottom:28},error:{color:'#B83131',fontSize:16,marginBottom:12},button:{backgroundColor:cyan,borderRadius:6,minHeight:48,justifyContent:'center',alignItems:'center'},buttonText:{fontSize:17,color:theme.ink,fontWeight:'700'},link:{fontSize:16,color:theme.ink,textAlign:'center',paddingVertical:13},demo:{backgroundColor:theme.tint,borderRadius:10,padding:16,marginBottom:18},demoTitle:{fontSize:theme.type.body,fontWeight:'700',color:ink,textAlign:'center'},note:{fontSize:theme.type.caption,color:theme.muted,textAlign:'center',lineHeight:22,marginTop:10}});
