import {theme} from './theme';
import React,{useState} from 'react';
import {View,Text,Pressable,TextInput,StyleSheet} from 'react-native';
import Icon from './Icon';
const ink=theme.ink,cyan=theme.brand;
const faqs=[{q:'When will my order arrive?',a:'For this demo, open Orders to see the estimated delivery date and tracking updates for each order.'},{q:'Which products fit my machine?',a:'Products shows supplies assigned to your location’s machines. Quick order lets you select a specific machine and find its syrups and accessories.'},{q:'How do I repeat a previous order?',a:'Use Reorder all on Home, or open an order and choose Reorder these items. Review quantities in your cart before checkout.'},{q:'How do I update my account details?',a:'Open Account to edit your contact email, shipping and billing addresses, or email preferences.'},{q:'Where can I get equipment help?',a:'Choose Call us or Chat and have your company location and machine details ready. These contact options are local demo previews.'}];
export default function SupportScreen(){
 const [section,setSection]=useState(null),[openFaq,setOpenFaq]=useState(null),[draft,setDraft]=useState(''),[messages,setMessages]=useState([]),[callPreview,setCallPreview]=useState(false);
 const send=()=>{if(!draft.trim())return;setMessages(m=>[...m,{text:draft.trim(),from:'you'},{text:'Thanks, John. This is a demo chat preview. No message has been sent to the Frozen Brothers team.',from:'support'}]);setDraft('')};
 return <View style={s.page}><Text style={s.title}>How can we help?</Text><View style={s.banner}><Icon name="support" size={32} color={theme.ink}/><View style={{flex:1}}><Text style={s.bold}>Here to keep you serving</Text><Text style={s.small}>Orders, account questions & equipment support</Text></View></View>{[['call','phone','Call us','Speak to the Frozen Brothers team'],['chat','chat','Chat','Start a conversation with support'],['faq','help','FAQs','Find answers to common questions']].map(([id,icon,title,description])=><Pressable key={id} accessibilityRole="button" onPress={()=>setSection(section===id?null:id)} style={[s.option,section===id&&{borderColor:cyan,backgroundColor:theme.tint}]}><View style={s.icon}><Icon name={icon} size={23}/></View><View style={{flex:1}}><Text style={s.bold}>{title}</Text><Text style={s.small}>{description}</Text></View><Icon name={section===id?'up':'right'} size={18}/></Pressable>)}
 {section==='call'&&<View style={s.panel}><Text style={s.heading}>Call Frozen Brothers</Text><Text style={s.text}>For orders, account access or equipment enquiries, speak to your Frozen Brothers support team.</Text><View style={s.info}><Text style={s.bold}>Your location</Text><Text style={s.small}>Vue Cinemas – Reading</Text><Text style={[s.small,{marginTop:8}]}>Have your order number or machine details ready.</Text></View><Pressable accessibilityRole="button" style={s.button} onPress={()=>setCallPreview(true)}><Icon name="phone" size={18} color={theme.ink}/><Text style={s.buttonText}>Call us · demo</Text></Pressable>{callPreview&&<Text accessibilityLiveRegion="polite" style={s.text}>Call preview ready. This demo does not dial a number. The live version will open the phone dialler with your support number.</Text>}<Text style={s.note}>Support phone number to be added for the live app.</Text></View>}
 {section==='chat'&&<View style={s.panel}><Text style={s.heading}>Chat with us</Text><View style={s.bubble}><Text style={s.text}>Hi John! How can we help with your order or machine today?</Text></View>{messages.map((m,i)=><View key={i} style={[s.bubble,m.from==='you'&&s.yourBubble]}><Text style={s.small}>{m.from==='you'?'You':'Frozen Brothers · demo'}</Text><Text style={s.text}>{m.text}</Text></View>)}<TextInput accessibilityLabel="Support chat message" placeholder="Type your message…" value={draft} onChangeText={setDraft} onSubmitEditing={send} multiline style={s.input}/><Pressable accessibilityRole="button" disabled={!draft.trim()} onPress={send} style={[s.button,!draft.trim()&&{backgroundColor:'#C7D8E0'}]}><Icon name="chat" size={18} color={theme.ink}/><Text style={s.buttonText}>Send · demo</Text></Pressable></View>}
 {section==='faq'&&<View style={s.panel}><Text style={s.heading}>Frequently asked questions</Text>{faqs.map((f,i)=><View key={f.q} style={s.faq}><Pressable accessibilityRole="button" onPress={()=>setOpenFaq(openFaq===i?null:i)} style={s.faqHeading}><Text style={[s.bold,{flex:1}]}>{f.q}</Text><Icon name={openFaq===i?'up':'down'} size={17}/></Pressable>{openFaq===i&&<Text style={s.text}>{f.a}</Text>}</View>)}</View>}
 <Text style={[s.note,{marginTop:24}]}>Frozen Brothers · support for your business</Text></View>
}
const s=StyleSheet.create({page:{paddingHorizontal:24,paddingVertical:10},title:{fontSize:theme.type.title,fontWeight:'800',color:ink},sub:{fontSize:16,color:theme.ink,marginTop:6},banner:{backgroundColor:theme.tint,padding:18,borderRadius:12,flexDirection:'row',alignItems:'center',gap:13,marginVertical:22},bold:{fontSize:theme.type.body,fontWeight:'700',color:ink,lineHeight:22},small:{fontSize:theme.type.caption,color:theme.muted,lineHeight:22},option:{borderWidth:1,borderColor:theme.border,borderRadius:12,padding:16,flexDirection:'row',alignItems:'center',gap:13,marginBottom:12},icon:{width:40,height:40,borderRadius:10,backgroundColor:theme.tint,alignItems:'center',justifyContent:'center'},panel:{padding:16,borderRadius:12,backgroundColor:theme.tint,marginTop:10},heading:{fontSize:theme.type.section,fontWeight:'700',color:ink,marginBottom:12},text:{fontSize:16,color:ink,lineHeight:24,marginVertical:8},info:{backgroundColor:'#fff',padding:14,borderRadius:8,marginVertical:12},button:{backgroundColor:cyan,padding:13,borderRadius:6,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:8,marginTop:12},buttonText:{fontSize:16,fontWeight:'700',color:'#fff'},note:{fontSize:theme.type.caption,color:theme.muted,lineHeight:22,textAlign:'center',marginTop:12},bubble:{backgroundColor:'#fff',borderRadius:10,padding:12,marginBottom:10},yourBubble:{backgroundColor:'#E2F2F6'},input:{borderWidth:1,borderColor:'#B6CBD6',borderRadius:8,padding:12,color:ink,fontSize:16,minHeight:65,backgroundColor:'#fff',marginTop:8},faq:{borderBottomWidth:1,borderColor:theme.border,paddingVertical:13},faqHeading:{flexDirection:'row',alignItems:'center',gap:10}});
